
general.import = [
	"~/.config/alacritty/everforest-dark.toml"
]
[env]
TERM = "xterm-256color"

[font]
normal = {family = "SpaceMono Nerd Font", style = "Regular"}
bold = {family = "SpaceMono Nerd Font", style = "Bold"}
size = 7.5

