
general.import = [
	"~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]
[env]
TERM = "xterm-256color"

[font]
normal = {family = "SpaceMono Nerd Font Mono", style = "Regular"}
bold = {family = "SpaceMono Nerd Font Mono", style = "Bold"}
size = 9

[cursor]
style.shape = "Beam"
style.blinking = "Always"
blink_interval = 500


[window]
opacity = 0.9
